In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/job_post/kariyer_12pt.csv')

In [ ]:
df

Unnamed: 0                                 Company & Position  \
0            0  \n                Software Engineer / Junior S...   
1            1  ['\n                Software Engineer \n      ...   
2            2  ['\n                Software Engineer\n       ...   
3            3  ['\n                Senior Software Engineer\n...   
4            4  ['\n                .Net Software Engineer\n  ...   
5            5  ['\n                Senior Software Engineer\n...   
6            6  ['\n                Software Engineer – Softwa...   
7            7  ['\n                Junior Software Support En...   
8            8  ['\n                Engineer - R&D (Software D...   
9            9  ['\n                Lead/Senior Software Testi...   
10          10  ['\n                Senior Embedded Software D...   
11          11  ['\n                Civil Engineer\n          ...   
12          12  ['\n                Civil Engineer\n          ...   

                                                 info  \
0   Job Type \n              Full-Time\n          ...   
1   ['Job Type \n              Full-Time\n        ...   
2   ['Job Type \n              Full-Time\n        ...   
3   ['Job Type \n              Full-Time\n        ...   
4   ['Job Type \n              Full-Time\n        ...   
5   ['Job Type \n              Full-Time\n        ...   
6   ['Job Type \n              Full-Time\n        ...   
7   ['Job Type \n              Full-Time\n        ...   
8   ['Job Type \n              Full-Time\n        ...   
9   ['Job Type \n              Full-Time\n        ...   
10  ['Job Type \n              Full-Time\n        ...   
11  ['Job Type \n              Full-Time\n        ...   
12  ['Job Type \n              Full-Time\n        ...   

                                          job details  
0   Do you want to work with talented and fun team...  
1   ["At inventiv, we are passionate about financi...  
2   ['Samsung Electronics is a global leader in te...  
3   ['Renaissance Heavy Industries – “RHI” carries...  
4   ['Qualifications & Job Decription\xa0Metasis T...  
5   ['ABOUT ICTERRAICterra is a global software en...  
6   ['JOB DESCRIPTIONAirties Software Licensing Te...  
7   ["We are a 23-year-young technology company st...  
8   ['Every moment is a development opportunity. O...  
9   ["QualificationsBachelor's degree in Electrica...  
10  ['We are looking for an Embedded Software Desi...  
11  ['Your ResponsibilitiesYou think it is time fo...  
12  ['PSE Engineering GmbH is a modern engineering...

In [ ]:
rena=df['job details'].iloc[3]
a=rena.replace("["," ")
b=a.replace(']', " ")


In [ ]:
b

" 'Renaissance Heavy Industries – “RHI” carries out the heavy industry projects in all leading sectors: hydrocarbons, power, metallurgy and mining, as well as processing plants, in Russia.In cooperation with its sister companies and through strategic partnerships, RHI provides engineering, procurement, construction, operation and management services for large-scale projects.We are looking for a “Senior Software Engineer”, to work remotely in coordination with our dynamic team in Moscow Office!What we expect you to have;Bachelor’s degree in Computer Engineering, Software Engineering or in related fields,At least 7 years of experience in software development, especially in C# application development on .NET platform,Knowledge and experience in object-oriented programming, architectural structures and designs, multi-layered architecture,Experience in Microservice architectures,Proficiency in .NET and .NET Core Framework,Knowledge and experience in developing MVC and SPA applications,Exper

In [ ]:
print(type(rena))

<class 'str'>


In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp(b)
sentences_rena = []

for sent in doc.sents:
  sentences_rena.append(sent.text)

print(sentences_rena)

[" 'Renaissance Heavy Industries – “RHI” carries out the heavy industry projects in all leading sectors: hydrocarbons, power, metallurgy and mining, as well as processing plants, in Russia.", 'In cooperation with its sister companies and through strategic partnerships, RHI provides engineering, procurement, construction, operation and management services for large-scale projects.', 'We are looking for a “Senior Software Engineer”, to work remotely in coordination with our dynamic team in Moscow Office!What we expect you to have;Bachelor’s degree in Computer Engineering, Software Engineering or in related fields,At least 7 years of experience in software development, especially in C# application development on .NET platform,Knowledge and experience in object-oriented programming, architectural structures and designs, multi-layered architecture,Experience in Microservice architectures,Proficiency in .NET', 'and .NET', 'Core Framework,Knowledge and experience in developing MVC and SPA app

In [ ]:
print(len(sentences_rena))

9


In [ ]:
print(sentences_rena[0])

 'Renaissance Heavy Industries – “RHI” carries out the heavy industry projects in all leading sectors: hydrocarbons, power, metallurgy and mining, as well as processing plants, in Russia.


In [ ]:
import re

In [ ]:
meta=df['job details'].iloc[4]
m2=meta.replace("\\xa0"," ")
#m1= m2.replace("\\\'", " " )

m2

'[\'Qualifications & Job Decription Metasis Technology, founded in 2009, is a leading software development company which provides consulting, training and project based software development, and offers solutions to organizations mostly from finance, telecommunication, public and retail fields which are competing in the national and international markets. A great opportunity has arisen to join the Software Development Department as a ".NET Software Engineer" in different positions and levels of expertise. · Bachelor\\\'s degree in Computer Engineering, Computer Science or another related field from an accredited 4 year university· At least 2+ years of hands-on development experience in .NET technologies· Excellent analytical and creative problem solving skills· Excellent communication skills· Experience of Object Oriented Design Methodologies, Design Patterns.· Experience in developing solutions using software tools like Microsoft Visual Studio, TFS.· Experience in SQL Query troubleshoo

In [ ]:
print(type(meta))

<class 'str'>


In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp(m2)
sentences_meta = []

for sent in doc.sents:
  sentences_meta.append(sent.text)

print(sentences_meta)

["['Qualifications & Job Decription Metasis Technology, founded in 2009, is a leading software development company which provides consulting, training and project based software development, and offers solutions to organizations mostly from finance, telecommunication, public and retail fields which are competing in the national and international markets.", 'A great opportunity has arisen to join the Software Development Department as a ".NET Software Engineer" in different positions and levels of expertise.', '·', "Bachelor\\'s degree in Computer Engineering, Computer Science or another related field from an accredited 4 year university· At least 2+ years of hands-on development experience in .NET technologies· Excellent analytical and creative problem solving skills· Excellent communication skills· Experience of Object Oriented Design Methodologies, Design Patterns.·", 'Experience in developing solutions using software tools like Microsoft Visual Studio, TFS.·', 'Experience in SQL Que

In [ ]:
print(len(sentences_meta))

15


In [ ]:
print(sentences_meta[5])

Experience in SQL Query troubleshooting/performance tuning .


In [ ]:
sentences_meta.pop(2)

'·'

In [ ]:
sentences_meta.pop(5)

'·'

In [ ]:
print(len(sentences_meta))

13


In [ ]:
bs=df['job details'].iloc[11]
BSH=bs.replace("\\xa0"," ")
BSH

"['Your ResponsibilitiesYou think it is time for something different? Then you are at the right place ! You will be working in an exciting, international environment and contributing personally to the company’s success. Expect exciting projects and versatile tasks, such as/Managing and supporting construction projects, preparing drawings, technical specifications, bill of quantities and price analysis/Monitoring and inspecting the conditions of construction areas in terms of quality, quantity and time, ensuring construction works fits to the designs, specifications and standarts. Finding solutions to the technical problems/Preparing quantitiy lists and specifications for construction works. Checking progress payment bills. Assists in the official permission processes, such as building permits and occupancy permits/Managing and supporting construction projects. Expertising to the users in case of a technical question, problem or a new construction idea. Participating temporary and final

In [ ]:
nlp = spacy.load("en_core_web_sm")
doc = nlp(BSH)
sentences_BSH = []

for sent in doc.sents:
  sentences_BSH.append(sent.text)

print(sentences_BSH)

["['Your ResponsibilitiesYou think it is time for something different?", 'Then you are at the right place !', 'You will be working in an exciting, international environment and contributing personally to the company’s success.', 'Expect exciting projects and versatile tasks, such as/Managing and supporting construction projects, preparing drawings, technical specifications, bill of quantities and price analysis/Monitoring and inspecting the conditions of construction areas in terms of quality, quantity and time, ensuring construction works fits to the designs, specifications and standarts.', 'Finding solutions to the technical problems/Preparing quantitiy lists and specifications for construction works.', 'Checking progress payment bills.', 'Assists in the official permission processes, such as building permits and occupancy permits/Managing and supporting construction projects.', 'Expertising to the users in case of a technical question, problem or a new construction idea.', 'Particip

In [ ]:
print(len(sentences_BSH))
print(sentences_BSH[9])

11
Evaluating repair/construction requests from users, planning and making it applied properlyYour Profile/Graduated from a Civil Engineering faculty of technical universities/Min 5 years experience on construction sites and design offices, preferably dealt with industrial construction and maintenance works in production areas /With a good degree of knowledge of AutoCAD, preferably able to use statical analyse programs, knowledge of MS Project and other office programs, ability to develop creative solutions /Strong


In [ ]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 45.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 50.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 19.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 62.5 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125942 sha256=47deec454696538021a2c02e987581e61ecc67a2ff148b68e5fbfd5830f8c934
  Stored in directory: /root/.cache/pip/wheels/71/67/06/162a3760c40d74dd40bc855d527008d26341c2b0ecf3e8e11f
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')

#encode the sentences
embeddings1 = model.encode(sentences_meta, convert_to_tensor=True)
embeddings2= model.encode(sentences_rena, convert_to_tensor=True)
embeddings3= model.encode(sentences_BSH, convert_to_tensor=True)
print(embeddings1)

#compute the similarity scores
cosine_scores = util.cos_sim(embeddings1, embeddings2)
cosine_scores2= util.cos_sim(embeddings1, embeddings3)

print(cosine_scores)

print(cosine_scores2)


tensor([[ 0.0415, -0.0210, -0.0397,  ..., -0.0122,  0.0713, -0.0128],
        [-0.0403, -0.0594,  0.0268,  ..., -0.0095,  0.0046,  0.0090],
        [ 0.0143, -0.0050,  0.0196,  ...,  0.0293, -0.0472,  0.0388],
        ...,
        [-0.0592,  0.0771, -0.0210,  ...,  0.0693,  0.0939,  0.0017],
        [ 0.0244, -0.0111, -0.0925,  ...,  0.0106, -0.0339,  0.0255],
        [-0.0953,  0.0486, -0.0226,  ...,  0.0335,  0.0783, -0.0287]])
tensor([[ 0.2451,  0.3267,  0.2662,  0.2073,  0.3655,  0.2393,  0.1945,  0.2992,
          0.3203],
        [ 0.1111,  0.1933,  0.4989,  0.3538,  0.3665,  0.3298,  0.2027,  0.4452,
          0.3894],
        [ 0.0278,  0.1065,  0.4514,  0.2208,  0.3546,  0.2036,  0.1980,  0.3364,
          0.3603],
        [ 0.1163,  0.2404,  0.2650,  0.2756,  0.4900,  0.4183,  0.1458,  0.3751,
          0.3115],
        [ 0.0194, -0.0034,  0.0727,  0.0298,  0.2035,  0.1461,  0.0968,  0.0247,
          0.1165],
        [ 0.0570,  0.1045,  0.2264,  0.1605,  0.3874,  0.1904,  0.

In [ ]:
print(type(cosine_scores2))

<class 'torch.Tensor'>


In [ ]:
print(embeddings1.size())
print(embeddings2.size())
print(embeddings3.size())

print(cosine_scores.size())
print(cosine_scores2.size())

torch.Size([13, 384])
torch.Size([9, 384])
torch.Size([11, 384])
torch.Size([13, 9])
torch.Size([13, 11])


In [ ]:
import torch

# Select top 13 cosine similarity scores
k = 13
top_k_scores, top_k_indices = torch.topk(cosine_scores.view(-1), k=k)
top_k_scores2, top_k_indices2 = torch.topk(cosine_scores2.view(-1), k=k)

print(top_k_scores)
print(top_k_indices)

print(top_k_scores2)
print(top_k_indices2)

tensor([0.7018, 0.4989, 0.4900, 0.4655, 0.4514, 0.4452, 0.4442, 0.4183, 0.4049,
        0.4034, 0.3962, 0.3913, 0.3894])
tensor([ 58,  11,  31,  95,  20,  16,  85,  32, 113,  62,  67,  53,  17])
tensor([0.4449, 0.4226, 0.4130, 0.4128, 0.4083, 0.3884, 0.3574, 0.3533, 0.3270,
        0.3255, 0.3250, 0.3181, 0.3155])
tensor([ 31,  42,  20, 114,  64,  75, 113, 102, 119,  37,  40,  65,  32])


In [ ]:
average_score = torch.mean(top_k_scores)
average_score2 = torch.mean(top_k_scores2)

print("Average cosine similarity score of the top {} pairs of sentences_meta and _sentences_rena: {:.4f}".format(k, average_score))
print("Average cosine similarity score of the top {} pairs of sentences_meta and _sentences_BSH: {:.4f}".format(k, average_score2))

Average cosine similarity score of the top 13 pairs of sentences_meta and _sentences_rena: 0.4539
Average cosine similarity score of the top 13 pairs of sentences_meta and _sentences_BSH: 0.3702
